# Generated by Django 3.2.4 on 2021-06-20 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('phoneNumber', models.CharField(blank=True, max_length=40, null=True, verbose_name='Numero telefonico')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Empresa')),
                ('prefix', models.CharField(blank=True, max_length=10, null=True, verbose_name='Prefijo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='FieldSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentativeDate', models.DateField(blank=True, null=True, verbose_name='Fecha Tentativa')),
                ('proposedDate', models.DateField(blank=True, null=True, verbose_name='Fecha Propuesta')),
                ('fieldSurveyDate', models.DateField(blank=True, null=True, verbose_name='Fecha Lev. Campo')),
                ('conclusionDate', models.DateField(blank=True, null=True, verbose_name='Fecha de Conclusión')),
                ('downloadedData', models.DateField(blank=True, null=True, verbose_name='Fecha Descarga Datos')),
            ],
            options={
                'verbose_name': 'Levantamiento de Campo',
                'verbose_name_plural': 'Levantamientos de Campo',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeService', models.CharField(max_length=40, verbose_name='Tipo Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Solicitudes')),
                ('deliveryDate', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega')),
                ('plan', models.ImageField(default='null', upload_to='planos', verbose_name='Plano')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=15, verbose_name='Estado')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.customers', verbose_name='Cliente')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.services', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armedInformation', models.DateField(blank=True, null=True, verbose_name='Info. Armada')),
                ('alignedPlan', models.DateField(blank=True, null=True, verbose_name='Plano Alineado')),
                ('downloadedPhotos', models.DateField(blank=True, null=True, verbose_name='Fotos descargadas')),
                ('sketch', models.DateField(blank=True, null=True, verbose_name='Dibujo de Croquis')),
                ('drafting', models.DateField(blank=True, null=True, verbose_name='Redacción del Doc.')),
                ('review', models.DateField(blank=True, null=True, verbose_name='Revisión')),
                ('finalReview', models.DateField(blank=True, null=True, verbose_name='Revisón Final')),
                ('submittedReport', models.DateField(blank=True, null=True, verbose_name='Reporte enviado el:')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.fieldsurvey', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
            },
        ),
        migrations.CreateModel(
            name='Replant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armedInformation', models.DateField(blank=True, null=True, verbose_name='Info. Armada')),
                ('alignedPlan', models.DateField(blank=True, null=True, verbose_name='Plano Alineado')),
                ('replantingPoints', models.DateField(blank=True, null=True, verbose_name='Rep. Puntos en sitio')),
                ('downloadedPhotos', models.DateField(blank=True, null=True, verbose_name='Fotos descargadas')),
                ('sketch', models.DateField(blank=True, null=True, verbose_name='Laminas Terminadas')),
                ('drafting', models.DateField(blank=True, null=True, verbose_name='Redacción del Doc.')),
                ('review', models.DateField(blank=True, null=True, verbose_name='Revisión')),
                ('submittedReport', models.DateField(blank=True, null=True, verbose_name='Reporte entregado el:')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.fieldsurvey', verbose_name='Solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='levelCurves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw', models.DateField(blank=True, null=True, verbose_name='Fecha Dibujo')),
                ('sketch', models.DateField(blank=True, null=True, verbose_name='Laminas Terminadas')),
                ('review', models.DateField(blank=True, null=True, verbose_name='Revisión')),
                ('submittedCurves', models.DateField(blank=True, null=True, verbose_name='Curvas entregadas el:')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.fieldsurvey', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Curvas de Nivel',
                'verbose_name_plural': 'Curvas de Nivel',
            },
        ),
        migrations.AddField(
            model_name='fieldsurvey',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.solicitudes', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='customers',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.empresas'),
        ),
        migrations.CreateModel(
            name='Corrections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloadedMinute', models.DateField(blank=True, null=True, verbose_name='Minuta Descargada')),
                ('errorReview', models.DateField(blank=True, null=True, verbose_name='Revisión de Errores')),
                ('corrections', models.DateField(blank=True, null=True, verbose_name='Correciones')),
                ('uploadedAPT', models.DateField(blank=True, null=True, verbose_name='Subido APT')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.fieldsurvey', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Correción',
                'verbose_name_plural': 'Correciones',
            },
        ),
        migrations.CreateModel(
            name='CadastralPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw', models.DateField(blank=True, null=True, verbose_name='Fecha Dibujo')),
                ('review', models.DateField(blank=True, null=True, verbose_name='Revisión')),
                ('uploadedAPT', models.DateField(blank=True, null=True, verbose_name='Subido APT')),
                ('advertisedPlano', models.DateField(blank=True, null=True, verbose_name='Plano Catastrado el:')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.fieldsurvey', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Plano Catastrado',
                'verbose_name_plural': 'Planos Catastrados',
            },
        ),
    ]
