# Generated by Django 3.2.4 on 2021-07-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
    ]
