# Generated by Django 3.2.4 on 2021-06-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='state',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=15, verbose_name='Estado'),
        ),
    ]
