# Generated by Django 3.2.4 on 2021-07-13 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20210711_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastralplans',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.fieldsurvey', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='corrections',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.fieldsurvey', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='fieldsurvey',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.solicitudes', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='levelcurves',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.fieldsurvey', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='replant',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.fieldsurvey', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.fieldsurvey', verbose_name='Solicitud'),
        ),
    ]
