# Generated by Django 3.2.4 on 2021-06-13 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_requests_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='state',
            new_name='status',
        ),
    ]
