# Generated by Django 3.2.4 on 2021-07-13 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20210712_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.empresas'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.customers', verbose_name='Cliente'),
        ),
    ]
