# Generated by Django 3.2.4 on 2021-06-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_rename_state_requests_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Solicitudes',
        ),
    ]
