# Generated by Django 3.2.4 on 2021-06-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_rename_requests_solicitudes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldsurvey',
            name='fieldSurveyDate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Lev. Campo'),
        ),
        migrations.AlterField(
            model_name='replant',
            name='armedInformation',
            field=models.DateField(blank=True, null=True, verbose_name='Info. Armada'),
        ),
        migrations.AlterField(
            model_name='replant',
            name='drafting',
            field=models.DateField(blank=True, null=True, verbose_name='Redacción del Doc.'),
        ),
        migrations.AlterField(
            model_name='replant',
            name='replantingPoints',
            field=models.DateField(blank=True, null=True, verbose_name='Rep. Puntos en sitio'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='armedInformation',
            field=models.DateField(blank=True, null=True, verbose_name='Info. Armada'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='drafting',
            field=models.DateField(blank=True, null=True, verbose_name='Redacción del Doc.'),
        ),
    ]
