# Generated by Django 3.2.4 on 2021-07-13 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20210712_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.services', verbose_name='Servicio'),
        ),
    ]
