# Generated by Django 3.2.4 on 2021-07-13 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_solicitudes_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastralplans',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.fieldsurvey', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='corrections',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.fieldsurvey', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.empresas'),
        ),
        migrations.AlterField(
            model_name='fieldsurvey',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.solicitudes', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='levelcurves',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.fieldsurvey', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='replant',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.fieldsurvey', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.fieldsurvey', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.customers', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.services', verbose_name='Servicio'),
        ),
    ]
