# Generated by Django 3.2.4 on 2021-07-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20210712_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastralplans',
            old_name='request',
            new_name='lev_campo_id',
        ),
        migrations.RenameField(
            model_name='corrections',
            old_name='request',
            new_name='lev_campo_id',
        ),
        migrations.RenameField(
            model_name='fieldsurvey',
            old_name='request',
            new_name='solicitud_id',
        ),
        migrations.RenameField(
            model_name='levelcurves',
            old_name='request',
            new_name='lev_campo_id',
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='request',
            new_name='lev_campo_id',
        ),
        migrations.RenameField(
            model_name='solicitudes',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='solicitudes',
            old_name='service',
            new_name='service_id',
        ),
    ]
