# Generated by Django 3.2.4 on 2021-07-17 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20210716_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replant',
            old_name='request',
            new_name='lev_campo_id',
        ),
    ]
