# Generated by Django 3.2.4 on 2021-07-18 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_rename_request_replant_lev_campo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastralplans',
            name='lev_campo_id',
        ),
        migrations.RemoveField(
            model_name='corrections',
            name='lev_campo_id',
        ),
        migrations.RemoveField(
            model_name='levelcurves',
            name='lev_campo_id',
        ),
        migrations.RemoveField(
            model_name='replant',
            name='lev_campo_id',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='lev_campo_id',
        ),
        migrations.AddField(
            model_name='cadastralplans',
            name='solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.solicitudes', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='corrections',
            name='cadastral_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.cadastralplans', verbose_name='Catastro'),
        ),
        migrations.AddField(
            model_name='levelcurves',
            name='solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.solicitudes', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='replant',
            name='solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.solicitudes', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='reports',
            name='solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.solicitudes', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='survey',
            field=models.BooleanField(default=True, verbose_name='Necesita Lev Campo?'),
        ),
    ]
