# Generated by Django 3.2.4 on 2021-07-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_auto_20210722_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='replant',
            name='files_replant',
            field=models.DateField(blank=True, null=True, verbose_name='Archivos de Replanteo'),
        ),
    ]
