# Generated by Django 3.2.4 on 2021-07-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_replant_files_replant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastralplans',
            name='advertisedPlano',
        ),
        migrations.AddField(
            model_name='cadastralplans',
            name='status',
            field=models.CharField(choices=[('Subido', 'Subido al APT'), ('Rechazado', 'Rechazado'), ('Cancelado', 'Cancelado'), ('Apelación', 'Apelación'), ('Oposicion', 'Oposicion'), ('Inscrito', 'Inscrito')], default='No tramitado', max_length=15, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cadastralplans',
            name='timbres',
            field=models.DateField(blank=True, null=True, verbose_name='Timbres comprados'),
        ),
    ]
