# Generated by Django 3.2.4 on 2021-07-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_auto_20210725_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastralplans',
            name='status',
            field=models.CharField(choices=[('Sin Tramitar', 'Sin Tramitar'), ('Subido', 'Subido al APT'), ('Rechazado', 'Rechazado'), ('Cancelado', 'Cancelado'), ('Apelación', 'Apelación'), ('Oposicion', 'Oposicion'), ('Inscrito', 'Inscrito')], default='Sin Tramitar', max_length=15, verbose_name='Estado'),
        ),
    ]
