# Generated by Django 3.2.4 on 2021-08-24 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_alter_cadastralplans_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Ocupations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Escriba el nombre de la ocupación', max_length=50, null=True, unique=True, verbose_name='Nombre de Ocupación')),
                ('area', models.CharField(help_text='Escriba el área de la ocupación', max_length=50, null=True, verbose_name='Área de la ocupación')),
            ],
            options={
                'verbose_name': 'Ocupación',
                'verbose_name_plural': 'Ocupaciones',
            },
        ),
        migrations.AddField(
            model_name='customers',
            name='canton',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cantón'),
        ),
        migrations.AddField(
            model_name='customers',
            name='cedula',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Cédula o pasaporte'),
        ),
        migrations.AddField(
            model_name='customers',
            name='direction',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='customers',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='customers',
            name='nacionalidad',
            field=models.CharField(choices=[('estranjero', 'Estranjero'), ('residente', 'Residente'), ('costarricense', 'Costarricense')], max_length=20, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='customers',
            name='province',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='Pendiente', max_length=15, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='Fecha de cotización')),
                ('description', models.CharField(help_text='Descripción de la cotización', max_length=100, null=True, verbose_name='Descripción')),
                ('contact', models.CharField(blank=True, help_text='Escriba el nombre del contacto', max_length=50, null=True, verbose_name='Contacto')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Digite el monto con 2 decimales', max_digits=9, verbose_name='Monto en $')),
                ('amount2', models.DecimalField(decimal_places=2, help_text='Digite el monto con 2 decimales', max_digits=9, verbose_name='Monto en ¢')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quote_customer', to='operations.customers', verbose_name='Cliente')),
                ('final_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.customers', verbose_name='Cliente Final')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='Preliminary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationMark', models.DateField(blank=True, null=True, verbose_name='Marca de Ubicación')),
                ('googleMaps', models.DateField(blank=True, null=True, verbose_name='GoogleMap')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], max_length=15, null=True, verbose_name='Estatus')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preliminary_assigned', to='operations.employees', verbose_name='Asignado a:')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.quotes', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Preliminar',
                'verbose_name_plural': 'Preliminares',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de factura #1')),
                ('amount_bill1', models.DecimalField(decimal_places=2, help_text='Digite el monto con 2 decimales', max_digits=9, verbose_name='Monto en $')),
                ('date_bill1', models.DateField(blank=True, null=True, verbose_name='Fecha de 1 factura')),
                ('bill2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de factura #2')),
                ('amount_bill2', models.DecimalField(decimal_places=2, help_text='Digite el monto con 2 decimales', max_digits=9, verbose_name='Monto en $')),
                ('date_bill2', models.DateField(blank=True, null=True, verbose_name='Fecha de 2 factura')),
                ('quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_quote', to='operations.quotes', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.AddField(
            model_name='employees',
            name='ocupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.ocupations', verbose_name='Ocupación'),
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armed_information', models.DateField(blank=True, null=True, verbose_name='Lev armado')),
                ('aligned_plan', models.DateField(blank=True, null=True, verbose_name='Plano Alineado')),
                ('sketch', models.DateField(blank=True, null=True, verbose_name='Croquis')),
                ('review', models.DateField(blank=True, null=True, verbose_name='Revisado')),
                ('status', models.CharField(choices=[('finalizado', 'Finalizado'), ('sin_concluir', 'Sin concluir')], default='Sin concluir', max_length=15, verbose_name='Estado')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='draw_assigned', to='operations.employees', verbose_name='Asignado a:')),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudDraw', to='operations.solicitudes', verbose_name='Solicitud')),
                ('task_manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.employees', verbose_name='Asignado a:')),
            ],
            options={
                'verbose_name': 'Dibujo',
                'verbose_name_plural': 'Dibujos',
            },
        ),
        migrations.AddField(
            model_name='cadastralplans',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cadastralplans_assigned', to='operations.employees', verbose_name='Asignado a:'),
        ),
        migrations.AddField(
            model_name='corrections',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='corrections_assigned', to='operations.employees', verbose_name='Asignado a:'),
        ),
        migrations.AddField(
            model_name='fieldsurvey',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fieldsurvey_assigned', to='operations.employees', verbose_name='Asignado a:'),
        ),
        migrations.AddField(
            model_name='levelcurves',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='levelcurves_assigned', to='operations.employees', verbose_name='Asignado a:'),
        ),
        migrations.AddField(
            model_name='replant',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replant_assigned', to='operations.employees', verbose_name='Asignado a:'),
        ),
        migrations.AddField(
            model_name='reports',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_assigned', to='operations.employees', verbose_name='Asignado a:'),
        ),
    ]
