# Generated by Django 3.2.4 on 2021-08-24 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_auto_20210823_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Escriba el nombre del departamento', max_length=50, null=True, verbose_name='Departamento:')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.RemoveField(
            model_name='ocupations',
            name='area',
        ),
        migrations.DeleteModel(
            name='Areas',
        ),
        migrations.AddField(
            model_name='ocupations',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.department', verbose_name='Departamento'),
        ),
    ]
