# Generated by Django 3.2.4 on 2021-08-24 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_auto_20210823_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocupations',
            name='department',
        ),
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('sin_concluir', 'Sin concluir'), ('finalizado', 'Finalizado')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
    ]
