# Generated by Django 3.2.4 on 2021-08-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_auto_20210823_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastralplans',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='draw',
            name='task_manager',
        ),
        migrations.RemoveField(
            model_name='levelcurves',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='levelcurves',
            name='sketch',
        ),
        migrations.RemoveField(
            model_name='replant',
            name='alignedPlan',
        ),
        migrations.RemoveField(
            model_name='replant',
            name='armedInformation',
        ),
        migrations.RemoveField(
            model_name='replant',
            name='sketch',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='alignedPlan',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='armedInformation',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='sketch',
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('sin_concluir', 'Sin concluir')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
    ]
