# Generated by Django 3.2.4 on 2021-08-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_auto_20210823_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('sin_concluir', 'Sin concluir'), ('finalizado', 'Finalizado')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de cotización'),
        ),
    ]
