# Generated by Django 3.2.4 on 2021-08-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_auto_20210823_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('sin_concluir', 'Sin concluir'), ('finalizado', 'Finalizado')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='status',
            field=models.CharField(choices=[('PR', 'Pendiente Revisión'), ('EC', 'Enviado al Cliente'), ('PE', 'Pendiente de Envio'), ('R', 'Rechazado'), ('A', 'Aprobada')], default='PR', max_length=15, null=True, verbose_name='Estatus'),
        ),
    ]
