# Generated by Django 3.2.4 on 2021-08-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_auto_20210823_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('sin_concluir', 'Sin concluir')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount_bill2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Digite el monto con 2 decimales', max_digits=9, null=True, verbose_name='Monto en $'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='amount2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Digite el monto con 2 decimales', max_digits=9, null=True, verbose_name='Monto en ¢'),
        ),
    ]
