# Generated by Django 3.2.4 on 2021-08-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_auto_20210823_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminary',
            name='document',
            field=models.DateField(blank=True, null=True, verbose_name='Modificación preliminar del documento'),
        ),
        migrations.AddField(
            model_name='preliminary',
            name='sketch',
            field=models.DateField(blank=True, null=True, verbose_name='Croquis Preliminares'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('sin_concluir', 'Sin concluir'), ('finalizado', 'Finalizado')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
    ]
