# Generated by Django 3.2.4 on 2021-08-28 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_auto_20210823_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldsurvey',
            name='tentativeDate',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='name',
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.quotes', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('sin_concluir', 'Sin concluir')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
    ]
