# Generated by Django 3.2.4 on 2021-09-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0028_auto_20210827_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='survey',
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='location',
            field=models.CharField(blank=True, help_text='Escriba la ubicación del lote', max_length=50, null=True, verbose_name='Localización'),
        ),
        migrations.AlterField(
            model_name='preliminary',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado'), ('enProceso', 'En proceso')], max_length=15, null=True, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado'), ('En proceso', 'En proceso'), ('Entregado', 'Entregado'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=15, verbose_name='Estado'),
        ),
    ]
