# Generated by Django 3.2.4 on 2021-09-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_auto_20210909_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelcurves',
            name='draw',
            field=models.DateField(blank=True, null=True, verbose_name='Dibujo'),
        ),
        migrations.AddField(
            model_name='levelcurves',
            name='presentation',
            field=models.DateField(blank=True, null=True, verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('sin_concluir', 'Sin concluir')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
    ]
