# Generated by Django 3.2.4 on 2021-09-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_auto_20210909_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='replant',
            name='armed_info',
            field=models.DateField(blank=True, null=True, verbose_name='Info. Armada'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('sin_concluir', 'Sin concluir'), ('finalizado', 'Finalizado')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
    ]
