# Generated by Django 3.2.4 on 2021-09-10 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0031_auto_20210909_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsurvey',
            name='armed_information',
            field=models.DateField(blank=True, null=True, verbose_name='Info. armada'),
        ),
        migrations.AddField(
            model_name='reports',
            name='assigned_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_assigned2', to='operations.employees', verbose_name='Asignado a:'),
        ),
        migrations.AddField(
            model_name='reports',
            name='sketch',
            field=models.DateField(blank=True, null=True, verbose_name='Croquis'),
        ),
    ]
