# Generated by Django 3.2.4 on 2021-09-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0033_alter_draw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsurvey',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado'), ('En proceso', 'En proceso'), ('Entregado', 'Entregado'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=15, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='levelcurves',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado'), ('En proceso', 'En proceso'), ('Entregado', 'Entregado'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='En Proceso', max_length=15, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='reports',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado'), ('En proceso', 'En proceso'), ('Entregado', 'Entregado'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='En Proceso', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('sin_concluir', 'Sin concluir'), ('finalizado', 'Finalizado')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='preliminary',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado'), ('enProceso', 'En proceso')], default='Pendiente', max_length=15, null=True, verbose_name='Estatus'),
        ),
    ]
