# Generated by Django 3.2.4 on 2021-09-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0034_auto_20210927_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastralplans',
            name='review',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Revisión'),
        ),
        migrations.AlterField(
            model_name='cadastralplans',
            name='timbres',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Timbres comprados'),
        ),
        migrations.AlterField(
            model_name='cadastralplans',
            name='uploadedAPT',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Subido APT'),
        ),
        migrations.AlterField(
            model_name='corrections',
            name='corrections',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Correciones'),
        ),
        migrations.AlterField(
            model_name='corrections',
            name='downloadedMinute',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Minuta Descargada'),
        ),
        migrations.AlterField(
            model_name='corrections',
            name='errorReview',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Revisión de Errores'),
        ),
        migrations.AlterField(
            model_name='corrections',
            name='uploadedAPT',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Subido APT'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='aligned_plan',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Plano Alineado'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='armed_information',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Lev armado'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='review',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Revisado'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='sketch',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Croquis'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('sin_concluir', 'Sin concluir')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fieldsurvey',
            name='armed_information',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Info. armada'),
        ),
        migrations.AlterField(
            model_name='fieldsurvey',
            name='conclusionDate',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Fecha de Conclusión'),
        ),
        migrations.AlterField(
            model_name='fieldsurvey',
            name='downloadedData',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Fecha Descarga Datos'),
        ),
        migrations.AlterField(
            model_name='fieldsurvey',
            name='fieldSurveyDate',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Fecha Lev. Campo'),
        ),
        migrations.AlterField(
            model_name='fieldsurvey',
            name='proposedDate',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Fecha Propuesta'),
        ),
        migrations.AlterField(
            model_name='levelcurves',
            name='draw',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Dibujo'),
        ),
        migrations.AlterField(
            model_name='levelcurves',
            name='presentation',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='levelcurves',
            name='review',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Revisión'),
        ),
        migrations.AlterField(
            model_name='levelcurves',
            name='submittedCurves',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Curvas entregadas el:'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date_bill1',
            field=models.DateField(blank=True, help_text='Colocar Fecha mm/dd/año', null=True, verbose_name='Fecha de 1 factura'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date_bill2',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Fecha de 2 factura'),
        ),
        migrations.AlterField(
            model_name='preliminary',
            name='locationMark',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Marca de Ubicación'),
        ),
        migrations.AlterField(
            model_name='replant',
            name='armed_info',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Info. Armada'),
        ),
        migrations.AlterField(
            model_name='replant',
            name='downloadedPhotos',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Fotos descargadas'),
        ),
        migrations.AlterField(
            model_name='replant',
            name='drafting',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Redacción del Doc.'),
        ),
        migrations.AlterField(
            model_name='replant',
            name='files_replant',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Archivos de Replanteo'),
        ),
        migrations.AlterField(
            model_name='replant',
            name='replantingPoints',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Rep. Puntos en sitio'),
        ),
        migrations.AlterField(
            model_name='replant',
            name='review',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Revisión'),
        ),
        migrations.AlterField(
            model_name='replant',
            name='submittedReport',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Reporte entregado el:'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='downloadedPhotos',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Fotos descargadas'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='drafting',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Redacción del Doc.'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='finalReview',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Revisón Final'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='review',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Revisión'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='sketch',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Croquis'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='submittedReport',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Reporte enviado el:'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='deliveryDate',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Fecha Entrega'),
        ),
    ]
