# Generated by Django 3.2.4 on 2021-10-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0035_auto_20210927_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('sin_concluir', 'Sin concluir'), ('finalizado', 'Finalizado')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='plan',
            field=models.URLField(blank=True, default='null', help_text='Link del plano, por favor', verbose_name='Plano'),
        ),
    ]
