# Generated by Django 3.2.4 on 2021-10-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0038_auto_20211005_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='nacionalidad',
            field=models.CharField(choices=[('Extranjero', 'Extranjero'), ('Residente', 'Residente'), ('Costarricense', 'Costarricense')], max_length=20, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('sin_concluir', 'Sin concluir'), ('finalizado', 'Finalizado')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fieldsurvey',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Entregado', 'Entregado'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='levelcurves',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Entregado', 'Entregado'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='En Proceso', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount_bill1',
            field=models.DecimalField(decimal_places=2, help_text='Digite el monto (máximo 2 decimales)', max_digits=9, null=True, verbose_name='Monto en $'),
        ),
        migrations.AlterField(
            model_name='preliminary',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado'), ('En Proceso', 'En proceso')], default='Pendiente', max_length=15, null=True, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Entregado', 'Entregado'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='En Proceso', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado'), ('En proceso', 'En proceso'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=15, verbose_name='Estado'),
        ),
    ]
