# Generated by Django 3.2.4 on 2021-10-06 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0041_auto_20211006_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastralplans',
            name='solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudCadastral', to='operations.quotes', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudDraw', to='operations.quotes', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='fieldsurvey',
            name='solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.quotes', verbose_name='solicitudField'),
        ),
        migrations.AlterField(
            model_name='levelcurves',
            name='solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudLevel', to='operations.quotes', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='final_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.customers', verbose_name='Cliente Final'),
        ),
        migrations.AlterField(
            model_name='replant',
            name='solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudReplant', to='operations.quotes', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudReport', to='operations.quotes', verbose_name='Solicitud'),
        ),
    ]
