# Generated by Django 3.2.4 on 2021-10-07 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0042_auto_20211006_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastralplans',
            name='solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudCadastral', to='operations.quotes', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='corrections',
            name='cadastral_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.cadastralplans', verbose_name='Catastro'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.empresas'),
        ),
        migrations.AlterField(
            model_name='fieldsurvey',
            name='solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.quotes', verbose_name='solicitudField'),
        ),
        migrations.AlterField(
            model_name='levelcurves',
            name='solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudLevel', to='operations.quotes', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='replant',
            name='solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudReplant', to='operations.quotes', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudReport', to='operations.quotes', verbose_name='Solicitud'),
        ),
    ]
