# Generated by Django 3.2.4 on 2021-10-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0043_auto_20211006_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('sin_concluir', 'Sin concluir'), ('finalizado', 'Finalizado')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
    ]
