# Generated by Django 3.2.4 on 2021-10-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0044_auto_20211007_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='note',
        ),
        migrations.AddField(
            model_name='payments',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
    ]
