# Generated by Django 3.2.4 on 2021-10-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0045_auto_20211007_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount_bill1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Digite el monto (máximo 2 decimales)', max_digits=9, null=True, verbose_name='Monto en $'),
        ),
    ]
