# Generated by Django 3.2.4 on 2021-10-09 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0046_alter_payments_amount_bill1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastralplans',
            name='apt',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='APT lleno'),
        ),
        migrations.AddField(
            model_name='cadastralplans',
            name='draw_plan',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Planos dibujados'),
        ),
        migrations.AddField(
            model_name='cadastralplans',
            name='minute_review',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Revisión Minuta'),
        ),
        migrations.AddField(
            model_name='cadastralplans',
            name='process_fly',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Vuelo procesado'),
        ),
        migrations.AddField(
            model_name='cadastralplans',
            name='protocolo',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Protocolo lleno'),
        ),
        migrations.AddField(
            model_name='cadastralplans',
            name='signed_protocol',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Protocolo comprado'),
        ),
        migrations.AddField(
            model_name='cadastralplans',
            name='visado',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Visado'),
        ),
        migrations.AddField(
            model_name='fieldsurvey',
            name='contact',
            field=models.DateField(blank=True, null=True, verbose_name='Contactar sitio'),
        ),
        migrations.AddField(
            model_name='fieldsurvey',
            name='fly_drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_drone', to='operations.employees', verbose_name='Uso de Drone'),
        ),
        migrations.AddField(
            model_name='fieldsurvey',
            name='gnss_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_gnss', to='operations.employees', verbose_name='Uso de GNSS'),
        ),
        migrations.AddField(
            model_name='fieldsurvey',
            name='station_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_station', to='operations.employees', verbose_name='Uso de estación'),
        ),
        migrations.AddField(
            model_name='levelcurves',
            name='process_fly',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Vuelo procesado'),
        ),
        migrations.AddField(
            model_name='preliminary',
            name='downloaded_plans',
            field=models.DateField(blank=True, null=True, verbose_name='Descarga de Planos'),
        ),
        migrations.AddField(
            model_name='preliminary',
            name='draw_plans',
            field=models.DateField(blank=True, null=True, verbose_name='Dibujo de Planos'),
        ),
        migrations.AddField(
            model_name='preliminary',
            name='google_to_group',
            field=models.DateField(blank=True, null=True, verbose_name='Google enviado al Grupo'),
        ),
        migrations.AddField(
            model_name='preliminary',
            name='schedule_service',
            field=models.DateField(blank=True, null=True, verbose_name='Servicio agendado'),
        ),
        migrations.AddField(
            model_name='replant',
            name='process_fly',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Vuelo procesado'),
        ),
        migrations.AddField(
            model_name='reports',
            name='process_fly',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Vuelo procesado'),
        ),
    ]
