# Generated by Django 3.2.4 on 2021-10-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0047_auto_20211008_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='area',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='location',
        ),
        migrations.AddField(
            model_name='quotes',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='location',
            field=models.CharField(blank=True, help_text='Escriba la ubicación del lote', max_length=50, null=True, verbose_name='Localización'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('sin_concluir', 'Sin concluir')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
    ]
