# Generated by Django 3.2.4 on 2021-10-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0050_auto_20211009_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preliminary',
            options={'get_latest_by': ['-id'], 'verbose_name': 'Preliminar', 'verbose_name_plural': 'Preliminares'},
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('sin_concluir', 'Sin concluir'), ('finalizado', 'Finalizado')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
    ]
