# Generated by Django 3.2.4 on 2021-10-10 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0051_auto_20211009_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preliminary',
            options={'get_latest_by': ['id'], 'verbose_name': 'Preliminar', 'verbose_name_plural': 'Preliminares'},
        ),
    ]
