# Generated by Django 3.2.4 on 2021-10-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0055_alter_draw_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['-id'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='quotes',
            options={'ordering': ['-id'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
    ]
