# Generated by Django 3.2.4 on 2021-10-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0056_auto_20211010_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='empresas',
            options={'ordering': ['-id'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
