# Generated by Django 3.2.4 on 2021-10-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0057_auto_20211010_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastralplans',
            options={'ordering': ['-id'], 'verbose_name': 'Plano Catastrado', 'verbose_name_plural': 'Planos Catastrados'},
        ),
        migrations.AlterModelOptions(
            name='corrections',
            options={'ordering': ['-id'], 'verbose_name': 'Correción', 'verbose_name_plural': 'Correciones'},
        ),
        migrations.AlterModelOptions(
            name='empresas',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='fieldsurvey',
            options={'ordering': ['-id'], 'verbose_name': 'Levantamiento de Campo', 'verbose_name_plural': 'Levantamientos de Campo'},
        ),
        migrations.AlterModelOptions(
            name='levelcurves',
            options={'ordering': ['-id'], 'verbose_name': 'Curvas de Nivel', 'verbose_name_plural': 'Curvas de Nivel'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['-id'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='preliminary',
            options={'ordering': ['-id'], 'verbose_name': 'Preliminar', 'verbose_name_plural': 'Preliminares'},
        ),
        migrations.AlterModelOptions(
            name='replant',
            options={'ordering': ['-id'], 'verbose_name': 'Replanteo', 'verbose_name_plural': 'Replanteos'},
        ),
        migrations.AlterModelOptions(
            name='reports',
            options={'ordering': ['-id'], 'verbose_name': 'Informe', 'verbose_name_plural': 'Informes'},
        ),
        migrations.AlterModelOptions(
            name='solicitudes',
            options={'ordering': ['-id'], 'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('sin_concluir', 'Sin concluir'), ('finalizado', 'Finalizado')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
    ]
