# Generated by Django 3.2.4 on 2021-10-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0060_auto_20211010_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='date_bill1',
            field=models.DateField(blank=True, help_text='Colocar Fecha mm/dd/año', null=True, verbose_name='Fecha de 1 factura'),
        ),
    ]
