# Generated by Django 3.2.4 on 2021-10-10 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0062_auto_20211010_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('cedula', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Cédula o pasaporte')),
                ('nacionalidad', models.CharField(choices=[('Extranjero', 'Extranjero'), ('Residente', 'Residente'), ('Costarricense', 'Costarricense')], max_length=20, null=True, verbose_name='Nacionalidad')),
                ('phoneNumber', models.CharField(blank=True, max_length=40, null=True, verbose_name='Numero telefonico')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Sub Cliente',
                'verbose_name_plural': 'Sub Clientes',
            },
        ),
        migrations.RemoveField(
            model_name='customers',
            name='empresa',
        ),
        migrations.AddField(
            model_name='customers',
            name='company',
            field=models.BooleanField(null=True, verbose_name='Es una empresa?'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='final_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.customers', verbose_name='Contratante en caso de ser empresa'),
        ),
        migrations.DeleteModel(
            name='Empresas',
        ),
    ]
