# Generated by Django 3.2.4 on 2021-10-10 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0063_auto_20211010_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_customers',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.customers'),
        ),
    ]
