# Generated by Django 3.2.4 on 2021-10-10 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0064_sub_customers_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='final_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.sub_customers', verbose_name='Contratante en caso de ser empresa'),
        ),
    ]
