# Generated by Django 3.2.4 on 2021-10-17 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0067_alter_sub_customers_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'Cliente / Empresa', 'verbose_name_plural': 'Clientes / Empresas'},
        ),
        migrations.AlterModelOptions(
            name='sub_customers',
            options={'verbose_name': 'Contacto de Empresa', 'verbose_name_plural': 'Contactos de Empresas'},
        ),
        migrations.RemoveField(
            model_name='customers',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='sub_customers',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sub_customers',
            name='lastName',
        ),
        migrations.AddField(
            model_name='customers',
            name='mobileNumber',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Numero Celular'),
        ),
        migrations.AddField(
            model_name='sub_customers',
            name='companyId',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.customers'),
        ),
        migrations.AddField(
            model_name='sub_customers',
            name='mobileNumber',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Numero Celular'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='nacionalidad',
            field=models.CharField(choices=[('Extranjero', 'Extranjero'), ('Costarricense', 'Costarricense')], max_length=20, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='final_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.sub_customers', verbose_name='En caso de ser Empresa, solicitado por:'),
        ),
        migrations.AlterField(
            model_name='sub_customers',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
