# Generated by Django 3.2.4 on 2021-10-17 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0068_auto_20211017_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_customers',
            old_name='companyId',
            new_name='company',
        ),
    ]
