# Generated by Django 3.2.4 on 2021-10-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('operations', '0071_auto_20211018_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_customers',
            options={'verbose_name': 'Colaborador de Empresa', 'verbose_name_plural': 'Colaboradores de Empresas'},
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('finalizado', 'Finalizado'), ('sin_concluir', 'Sin concluir')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='ocupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group', verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='sub_customers',
            name='company',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.customers', verbose_name='Empresa'),
        ),
        migrations.DeleteModel(
            name='Ocupations',
        ),
    ]
