# Generated by Django 3.2.4 on 2021-10-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('operations', '0072_auto_20211021_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Escriba el nombre de la ocupación', max_length=50, null=True, unique=True, verbose_name='Nombre de Ocupación')),
            ],
            options={
                'verbose_name': 'Ocupación',
                'verbose_name_plural': 'Ocupaciones',
            },
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('sin_concluir', 'Sin concluir'), ('finalizado', 'Finalizado')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group', verbose_name='Departamento'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AlterField(
            model_name='employees',
            name='ocupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='operations.ocupations', verbose_name='Ocupación'),
        ),
    ]
