# Generated by Django 3.2.4 on 2021-10-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0073_auto_20211021_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
    ]
