# Generated by Django 3.2.4 on 2021-10-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0074_alter_employees_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Colaborador en QT', 'verbose_name_plural': 'Colaboradores QT'},
        ),
        migrations.AlterModelOptions(
            name='ocupations',
            options={'verbose_name': 'Ocupación en QT', 'verbose_name_plural': 'Ocupaciones QT'},
        ),
        migrations.AlterField(
            model_name='services',
            name='typeService',
            field=models.CharField(max_length=40, verbose_name='Tipo Servicio'),
        ),
    ]
