# Generated by Django 3.2.4 on 2021-10-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0076_alter_draw_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='typeService',
            field=models.CharField(max_length=40, unique=True, verbose_name='Tipo Servicio'),
        ),
    ]
