# Generated by Django 3.2.4 on 2021-10-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0077_alter_services_typeservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('sin_concluir', 'Sin concluir'), ('finalizado', 'Finalizado')], default='Sin concluir', max_length=15, verbose_name='Estado'),
        ),
    ]
