# Generated by Django 3.2.4 on 2021-10-24 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0079_alter_draw_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastralplans',
            name='status',
            field=models.CharField(choices=[('Sin Tramitar', 'Sin Tramitar'), ('Subido al APT', 'Subido al APT'), ('Rechazado', 'Rechazado'), ('Cancelado', 'Cancelado'), ('Apelación', 'Apelación'), ('Oposicion', 'Oposicion'), ('Inscrito', 'Inscrito')], default='Sin Tramitar', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fieldsurvey',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fieldsurvey_assigned', to='operations.employees', verbose_name='Asignacion General a:'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='assigned_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_assigned2', to='operations.employees', verbose_name='Redacción asignado a:'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_assigned', to='operations.employees', verbose_name='Croquis asignado a:'),
        ),
        migrations.DeleteModel(
            name='Draw',
        ),
    ]
