# Generated by Django 3.2.4 on 2021-10-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0080_auto_20211024_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='date',
        ),
        migrations.AddField(
            model_name='quotes',
            name='date_answer',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Fecha de aprobación o rechazo:'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='date_request',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='date_send',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Cotización enviada el:'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Colocar Fecha dd/mm/año', null=True, verbose_name='Fecha de entrega:'),
        ),
    ]
