# Generated by Django 3.2.4 on 2021-10-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0081_auto_20211024_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='deliveryDate',
        ),
        migrations.AddField(
            model_name='cadastralplans',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='corrections',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='fieldsurvey',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='levelcurves',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='replant',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='replant',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Entregado', 'Entregado'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='Sin Tramitar', max_length=15, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='reports',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
    ]
