# Generated by Django 3.2.4 on 2021-10-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0083_preliminary_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastralplans',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='corrections',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='fieldsurvey',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='levelcurves',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='preliminary',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='replant',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentario'),
        ),
    ]
