# Generated by Django 3.2.4 on 2021-11-05 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0085_auto_20211102_0942'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER SEQUENCE operations_quotes_id_seq RESTART WITH 300;'
        )
    ]
